name: stft
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - numpy=1.15.4
  - pip=19.0.1
  - python=3.7.2
  - pytorch=1.0.1
  - scipy=1.2.0
  - setuptools=40.7.3
  - torchvision=0.2.1
  - wheel=0.32.3
  - librosa=0.6.3
  - pip:
    - tensorflow==1.13.0rc1


